import React from "react";
import BreadcrumbComp from "../../layout/shared/breadcrumb/BreadcrumbComp";
import FollowersChart from "@/app/components/widgets/charts/FollowersChart";
import ViewsChart from "@/app/components/widgets/charts/ViewsChart";
import EarnedChart from "@/app/components/widgets/charts/EarnedChart";
import TotalEarningChart from "@/app/components/widgets/charts/TotalEarnigs";
import CurrentValue from "@/app/components/widgets/charts/CurrentValue";
import YarlyBreakup from "@/app/components/widgets/charts/YarlyBreakup";
import MonthlyEarning from "@/app/components/widgets/charts/MonthlyEarcning";
import MostVisited from "@/app/components/widgets/charts/MostVisited";
import YearlySales from "@/app/components/widgets/charts/YearlySales";
import PageImpression from "@/app/components/widgets/charts/PageImpression";
import Customers from "@/app/components/widgets/charts/Customers";
import Projects from "@/app/components/widgets/charts/Projects";
import RevenueUpdates from "@/app/components/widgets/charts/RevenueUpdates";
import SalesOverview from "@/app/components/widgets/charts/SalesOverview";
import SalesProfit from "@/app/components/dashboards/ecommerce/SalesProfit";
import type { Metadata } from "next";
import ProductSales from "@/app/components/dashboards/ecommerce/ProductSales";
import MarketingReport from "@/app/components/dashboards/ecommerce/MarketingReport";
import Payments from "@/app/components/dashboards/ecommerce/Payments";
import AnnualProfit from "@/app/components/dashboards/ecommerce/AnnualProfit";
import Customer from "@/app/components/dashboards/analytics/Customer";
import AnalyticPayments from "@/app/components/dashboards/analytics/Payments";
import Products from "@/app/components/dashboards/analytics/Products";
import OverallBalance from "@/app/components/dashboards/crm/OverallBalance";
import ReturnOnInvest from "@/app/components/dashboards/crm/ReturnOnInvest";
import TotalFollowers from "@/app/components/dashboards/crm/TotalFollowers";
import TotalIncome from "@/app/components/dashboards/crm/TotalIncome";
import CurrentBalance from "@/app/components/dashboards/crm/CurrentBalance";
import DeliveryAnalytics from "@/app/components/dashboards/crm/DeliveryAnalytics";
import CrmMarketingReport from "@/app/components/dashboards/crm/CrmMareketingReport";

export const metadata: Metadata = {
  title: "Chart Widgets",
  description: "Generated by create next app",
};

const BCrumb = [
  {
    to: "/",
    title: "Home",
  },
  {
    title: "Charts",
  },
];
const Charts = () => {
  return (
    <>
      <BreadcrumbComp title="Charts" items={BCrumb} />
      <div className="grid grid-cols-12 gap-7">
        <div className="lg:col-span-3 md:col-span-6 col-span-12">
          <FollowersChart />
        </div>
        <div className="lg:col-span-3 md:col-span-6 col-span-12">
          <ViewsChart />
        </div>
        <div className="lg:col-span-3 md:col-span-6 col-span-12">
          <EarnedChart />
        </div>
        <div className="lg:col-span-3 md:col-span-6 col-span-12">
          <TotalEarningChart />
        </div>
        <div className="col-span-12">
          <CurrentValue />
        </div>
        <div className="lg:col-span-4 col-span-12">
          <YarlyBreakup />
          <MonthlyEarning />
          <MostVisited />
        </div>
        <div className="lg:col-span-4 col-span-12">
          <YearlySales />
          <PageImpression />
          <div className="grid grid-cols-12 gap-7 mt-[30px]">
            <div className="sm:col-span-6 col-span-12">
              <Customers />
            </div>
            <div className="sm:col-span-6 col-span-12">
              <Projects />
            </div>
          </div>
        </div>
        <div className="lg:col-span-4 col-span-12">
          <RevenueUpdates />
          <SalesOverview />
        </div>

        <div className="lg:col-span-8 col-span-12">
          <SalesProfit />
        </div>
        <div className="lg:col-span-4 col-span-12">
          <ProductSales />
        </div>
        <div className="lg:col-span-5 col-span-12">
          <MarketingReport />
        </div>
        <div className="lg:col-span-3 col-span-12">
          <Payments />
        </div>
        <div className="lg:col-span-4 col-span-12">
          <AnnualProfit />
        </div>

        <div className="lg:col-span-8 col-span-12">
          <OverallBalance />
        </div>
        <div className="lg:col-span-4 col-span-12">
          <ReturnOnInvest />
        </div>

        <div className="lg:col-span-4 col-span-12">
          <TotalFollowers />
        </div>
        <div className="lg:col-span-4 col-span-12">
          <TotalIncome />
        </div>
        <div className="lg:col-span-4 col-span-12">
          <CurrentBalance />
        </div>
        <div className="lg:col-span-7 col-span-12">
          <DeliveryAnalytics />
        </div>
        <div className="lg:col-span-5 col-span-12">
          <CrmMarketingReport />
        </div>
        <div className="lg:col-span-4 md:col-span-4 col-span-12">
          <Customer />
        </div>
        <div className="lg:col-span-4 md:col-span-4 col-span-12">
          <AnalyticPayments />
        </div>
        <div className="lg:col-span-4 md:col-span-4 col-span-12">
          <Products />
        </div>
      </div>
    </>
  );
};

export default Charts;
