import React from "react";
import BreadcrumbComp from "../../layout/shared/breadcrumb/BreadcrumbComp";
import ApexDoughnutChartCode from "@/app/components/charts/Code/ApexDoughnutChartCode";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Doughnut & Pie Chart",
  description: "Generated by create next app",
};

const BCrumb = [
  {
    to: "/",
    title: "Home",
  },
  {
    title: "Chart Apex Doughtnut",
  },
];
const DoughnutChart = () => {
  return (
    <>
      <BreadcrumbComp title="Chart Apex Doughtnut" items={BCrumb} />
      <ApexDoughnutChartCode />
    </>
  );
};

export default DoughnutChart;
