import { Button } from "@/components/ui/button";
import Link from "next/link";
import Image from "next/image";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Maintenance",
  description: "Generated by create next app",
};
const Maintenance = () => {
  return (
    <>
      <div className="h-screen flex items-center  justify-center bg-white dark:bg-darkgray">
        <div className="text-center">
          <Image
            src="/images/backgrounds/website-under-construction.svg"
            alt="maintenance"
            className="mb-4"
            width={500}
            height={500}
          />
          <h1 className="text-ld text-4xl mb-6">Maintenance Mode!!!</h1>
          <h6 className="text-xl text-ld">
            Website is Under Construction. Check back later!
          </h6>
          <Button color={"primary"} className="w-fit mt-6 mx-auto">
            <Link href="/"> Go Back to Home</Link>
          </Button>
        </div>
      </div>
    </>
  );
};

export default Maintenance;
