import { Card } from "@/components/ui/card";
import Link from "next/link";
import AuthForgotPassword from "../../authforms/AuthForgotPassword";
import { Button } from "@/components/ui/button";
import type { Metadata } from "next";
import FullLogo from "@/app/(DashboardLayout)/layout/shared/logo/Logo";
import CardBox from "@/app/components/shared/CardBox";
export const metadata: Metadata = {
  title: "Boxed Forgot Password Auth",
  description: "Generated by create next app",
};

const BoxedForgotpwd = () => {
  return (
    <>
      <div className="relative overflow-hidden h-screen bg-muted dark:bg-dark">
        <div className="flex h-full justify-center items-center px-4">
          <CardBox className="md:w-[450px] w-full border-none">
            <div className="flex justify-center pt-3">
              <FullLogo />
            </div>
            <p className="text-darklink text-sm text-center my-4">
              Please enter the email address associated with your account and We
              will email you a link to reset your password.
            </p>
            <AuthForgotPassword />
            <Button color={"lightprimary"} className="rounded-md w-full mt-3">
              <Link href="/auth/auth2/login">Back to Login</Link>
            </Button>
          </CardBox>
        </div>
      </div>
    </>
  );
};

export default BoxedForgotpwd;
